-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 10, 2021 at 06:45 AM
-- Server version: 10.4.18-MariaDB
-- PHP Version: 7.4.16

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `mobcom`
--

-- --------------------------------------------------------

--
-- Table structure for table `product_master`
--

CREATE TABLE `product_master` (
  `product_id` int(100) NOT NULL,
  `product_desc` varchar(10000) NOT NULL,
  `brand_id` int(100) NOT NULL,
  `model_number` varchar(255) NOT NULL,
  `model_name` varchar(255) NOT NULL,
  `model_colour` varchar(255) NOT NULL,
  `display_size` float NOT NULL,
  `display_resolution` varchar(255) NOT NULL,
  `operating_system` varchar(100) NOT NULL,
  `processor` varchar(255) NOT NULL,
  `internal_storage` int(100) NOT NULL,
  `ram` int(100) NOT NULL,
  `memory_card_available` varchar(100) NOT NULL,
  `primary_camera` varchar(255) NOT NULL,
  `secondary_camera` varchar(255) NOT NULL,
  `network_type` varchar(255) NOT NULL,
  `battery_capacity` int(6) NOT NULL,
  `mobile_width` float NOT NULL,
  `mobile_depth` float NOT NULL,
  `mobile_weight` float NOT NULL,
  `mobile_price` float NOT NULL,
  `mobile_availabilty` int(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `product_master`
--

INSERT INTO `product_master` (`product_id`, `product_desc`, `brand_id`, `model_number`, `model_name`, `model_colour`, `display_size`, `display_resolution`, `operating_system`, `processor`, `internal_storage`, `ram`, `memory_card_available`, `primary_camera`, `secondary_camera`, `network_type`, `battery_capacity`, `mobile_width`, `mobile_depth`, `mobile_weight`, `mobile_price`, `mobile_availabilty`) VALUES
(1, 'Meet Pixel 4a. It comes packed with the things you want most in a phone, for a lot less than you’d expect. And it’s unlocked – so you can pick the carrier and data plan that work best for you.', 1, 'G025J', 'Pixel 4a', 'Just Black', 14.73, '2340 x 1080', 'android 10', 'Qualcomm Snapdragon 730G', 128, 6, 'microSD', '12.2', '8', '4G VOLTE, 4G, 3G, 2G', 3140, 69, 144, 8, 143, 50),
(2, 'With better cameras, long-lasting battery life, powerful processor and enhanced stereo speakers, the iPhone 7 Plus takes your iPhone experience till date to the next level. Thanks to its vibrant display, sleek design and a water- and splash-resistant enclosure, this smartphone looks every bit as impressive as it is.', 7, '\r\nMN8X2HN/A', '\r\niPhone 7', '\r\nBlack', 11.94, '1334 x 750', 'IOS 12', '\r\nApple A10 Fusion 64-bit processor and Embedded M10 Motion Co-processor\r\n', 32, 2, '', '12MP Rear Camera', '\r\n7MP Front Camera', '3G, 4G LTE, GPRS, WiFi, EDGE', 2700, 67, 138, 138, 0, 0),
(3, 'And then there was Pro. A transformative triple‑camera system that adds tons of capability without complexity. An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro.\r\n\r\n', 7, '\r\nMHDG3HN/A', '\r\niPhone 11', '\r\nGreen', 15.49, '1792 x 828', '\r\niOS 14.2', 'A13 Bionic Chip', 64, 4, '', '12MP + 12MP', '12MP Front Camera', '\r\n4G VOLTE, 4G, 3G, 2G', 0, 76, 151, 194, 0, 0),
(4, 'And then there was Pro. A transformative triple‑camera system that adds tons of capability without complexity. An unprecedented leap in battery life. And a mind‑blowing chip that doubles down on machine learning and pushes the boundaries of what a smartphone can do. Welcome to the first iPhone powerful enough to be called Pro.\r\n\r\n', 7, '\r\nMGDL3HN/A', '\r\niPhone 12 Pro Max', '\r\nPacific Blue', 17.02, '\r\n2778 x 1284', '\r\niOS 14', 'A14 Bionic Chip with Next Generation Neural Engine', 512, 4, '', '12MP + 12MP + 12MP', '12MP Front Camera', '\r\n5G, 4G, 3G, 2G', 3500, 78, 161, 226, 0, 0),
(5, 'Description iPhone SE is the powerful 4.7-inch iPhone.¹ Features A13 Bionic, one of the fastest chips in a smartphone, for incredible performance in apps, games, and photography. Portrait mode for studio-quality portraits and six lighting effects. Next-generation Smart HDR for incredible detail across highlights and shadows. Cinematic-quality 4K video. And all the advanced features of iOS. With long battery life² and water resistance³, it\'s so much of the iPhone you love, in a not so big size.', 7, '\r\nMHGQ3HN/A', '\r\niPhone SE', 'White', 11.94, '\r\n1334 x 750', '\r\niOS 14.2', '\r\nA13 Bionic Chip with 3rd Gen Neural Engine', 64, 3, '', '\r\n12MP Rear Camera', '\r\n7MP Front Camera', '4G VOLTE, 4G, 3G, 2G', 2700, 67, 7, 148, 0, 0),
(6, 'Only iPhone No other phone is like iPhone. Only when hardware and software are designed together can they truly work together. Apple teams design the world’s best products, with the most innovative displays, chips, cameras, operating systems, and services. But just as important, the teams collaborate so that all the components of iPhone work together efficiently and beautifully. While this might seem like an obvious way to work, no other smartphone is made this way. And it makes all the difference. It means', 7, '\r\nMRY42HN/A', 'iPhone XR', '\r\nBlack', 15.5, '\r\n\r\n1792 x 828', '\r\niOS 12', '\r\nA12 Bionic Chip', 64, 3, '', '\r\n12MP Rear Camera', '7MP Front Camera', '\r\n3G, 4G, 2G', 2700, 76, 8, 194, 0, 0),
(7, 'Whether be it work or play, we need our phone assisting us all day long. The Asus Zenfone 3s Max with its impressive battery life and a plethora of useful features helps you breeze through everyday tasks with such ease.', 8, 'ZC520TL', 'Asus Zenfone 3 Max', 'Silver', 13.2, '1280 x 720', 'Android', 'MediaTek MT6737 64-bit', 32, 3, '32', '13', '5MP (Front camera)', 'dual SIM dual-standby (4G+4G)', 4130, 15, 1, 150, 0, 0),
(8, 'Meet the Asus Zenfone Max Pro (M1), whose power-packed features such as the loud speaker and a high-capacity battery, will elevate your smartphone experience to a different level. Its Dual-camera System with Bokeh is bound to make your pictures look beautiful. Not to forget, the FHD+ Display will make everything on screen look visually appealing.', 8, 'ZB601KL-4D101IN', 'Zenfone Max Pro M1', 'Silver', 15.21, '\r\n2160 x 1080', '\r\nAndroid Oreo 8.1', 'Qualcomm Snapdragon 636 Octa Core', 32, 3, '2TB', '13MP + 5MP', '\r\n8MP Front Camera', '\r\n3G, 4G VOLTE, 2G', 5000, 76, 8, 180, 0, 0),
(9, 'If you\'re looking for a smartphone that\'s robust and powerful, both, inside and outside, then your search ends here. Meet the ZenFone Max Pro M2 - the smartphone that comes loaded with innovative features, such as a Snapdragon 660 processor, a 5-magnet NXP speaker and Corning Gorilla Glass 6 protection, to make your mobile experience all the more seamless and secure.', 8, 'ZB630KL-4D001IN', 'ZenFone Max Pro M2', 'Blue', 15.9, '\r\n2280 x 1080', '\r\nAndroid Oreo 8.1', 'Qualcomm Snapdragon 660 Octa Core', 64, 4, '2TB', '\r\n12MP + 5MP', '\r\n13MP Front Camera', '\r\n3G, 4G VOLTE, 4G, 2G', 5000, 76, 9, 175, 0, 0),
(10, 'Robust, performance-oriented, and stylish, just like gamers, the ASUS ROG Phone 3 is a device meant for gaming. It is packed with multi-level processor cooling features so that your phone stays cool. It also comes with a whopping 6000 mAh battery to let you continue gaming for hours. With the presence of ultrasonic AirTriggers 3 with Dual Partition functionality, this phone even gives you the ability to enjoy console-like gaming.', 8, 'ZS661KS-6A039IN', '\r\nROG Phone 3', '\r\nBlack', 16.74, '2340 x 1080', '\r\nAndroid 10', '\r\nQualcomm Snapdragon 865+ (SM8250)', 128, 12, '', '64MP + 13MP + 5MP', '24MP Front Camera', '\r\n5G, 4G, 3G, 2G', 6000, 78, 10, 240, 0, 0),
(11, 'Get set for action-packed adventures with the ASUS ROG phone 2 which facilitates a blazing fast performance with great features for a seamless gaming experience. It comes with the robust ROG GameCool II cooling system to help you game for long hours, without worrying about the device being heated up. This smartphone’s 6000 mAh battery is enough to keep you hooked to your game for hours. What’s more, with features like the side-mounted ports and curved edges, this smartphone will be easy to hold and operate, no matter how you are gaming. This smartphone also comes with a dual-camera system (48 MP IMX586 main camera and a 13 MP secondary camera) and a 24 MP front camera to help you click stunning pictures or be a clear part of live streaming games.', 8, '\r\nZS660KL-1A017IN', 'ROG Phone II\r\n', '\r\nBlack', 16.74, '\r\n2340 x 1080', 'Android Pie 9', 'Qualcomm Snapdragon 855 Plus', 128, 8, '', '48MP + 13MP', '24MP Front Camera', '\r\n3G, 4G VOLTE, 4G, 2G', 6000, 78, 10, 240, 0, 0),
(12, 'The Honor 9X comes with a 16.73 cm (6.5) Full HD+ display that has a screen PPI of 391. With a screen-to-body ratio of 91%, watching movies, playing games and even reading books on this almost bezel-less display is a joy in itself. With the Honor FullView Display have an immersive and wonderful phone experience.', 9, '\r\nSTK-L22', '\r\n9X', '\r\nMidnight Blue', 16.74, '\r\n2340 x 1080', '\r\nAndroid Pie 9', '\r\nKirin 710F', 128, 4, '512', '48MP + 8MP + 2MP', '\r\n16MP Front Camera', '\r\n4G VOLTE, 3G, 2G', 4000, 77, 9, 197, 0, 0),
(13, 'Capture stunning images, wherever you go, with the HONOR 20 smartphone. Its four rear cameras (16 MP + 48 MP + 2 MP + 2 MP Macro) let you capture beautiful landscape images, eye-catching close-up shots, and bright images even under low-light conditions. Oh, and when you want to click a selfie, you can do so, with this smartphone’s 32 MP high-resolution front camera. This smartphone is powered by the Kirin 980 chipset and the GPU Turbo 3.0, thereby facilitating a lag-free performance, even while gaming.\r\n\r\n', 9, '\r\nYAL-AL00', '\r\n20', '\r\nMidnight Black', 15.9, '\r\n2340 x 1080', 'Android Pie 9.0', 'HiSilicon Kirin 980', 128, 6, '', '48MP + 2MP + 16MP\r\n', '32MP Front Camera', '\r\n3G, 4G VOLTE, 4G, 2G', 3750, 74, 8, 174, 0, 0),
(14, 'The LG G8X is a dual-screen mobile that lets you multitask like a pro, comes with a 360° freestop hinge that helps rotate the screen to any angle for the most comfortable view. The AI Action Shot feature helps you snap the action around you, while the stylish design and stunning display give you an immersive experience. This IP68 certified phone comes with an advanced 32 bit Hi-Fi Quad DAC that lets you enjoy your favourite music in a loud and clear fashion. The 3D surround sound along with stereo speakers only add on to the aural experience. Powered by the highly-efficient Qualcomm Snapdragon 855 chipset, the LG G8X comes equipped with a large 4000 mAh battery so that you can continue doing your favourite things as well as work side-by-side on the gorgeous dual-screen display.', 10, '\r\nLMG850EMW', '\r\nG8X', '\r\nBlack', 16.26, '\r\n2340 x 1080', 'Android Pie 9', '\r\nQualcomm Snapdragon™ 855 Octa-core', 128, 6, '2TB', '12MP + 13MP\r\n', '32MP Front Camera', '\r\n4G VOLTE, 3G', 4000, 76, 8, 191, 0, 0),
(15, 'Bid goodbye to constantly switching between two apps by getting the LG Velvet Dual-screen Smartphone. The dual screens help you multitask like a pro as you can simultaneously view two apps at the same time. You can even choose to detach the second screen and use the main screen as a normal smartphone. The 17.3 cm (6.8) cinematic pOLED widescreen display and stereo speakers help take your audio-visual experience to the next level. To top it off, the 4,300 mAh battery holds enough power to keep you entertained for almost an entire day.', 10, '\r\nLMG910EMW', 'Velvet Dual Screen', 'Aurora Silver', 17.27, '2460 x 1080', 'Android 10', 'Qualcomm Snapdragon 845', 128, 6, '2TB', '48MP + 8MP + 5MP', '16MP Front Camera', '\r\n4G VOLTE, 4G, 3G, 2G', 4300, 74, 8, 180, 0, 0),
(16, 'This LG phone will change the way you use your smartphone. While its swivel mode lets you rotate the screen of the phone for multitasking, the water-repellant coating provides protection from accidental splashes and downpours. What’s more, the Gimbal Motion Camera helps you shoot amazing content of moving objects by using various features.', 10, '\r\nLMF100EMW', 'Wing', '\r\nIllusion Sky', 17.27, '2460 x 1080', '\r\nAndroid 10', '\r\nQualcomm Snapdragon 765G', 128, 8, '2TB', '\r\n64MP + 13MP + 12MP', '32MP Front Camera', '5G, 4G VOLTE, 4G, 3G, 2G', 4000, 75, 11, 260, 0, 0),
(17, ' Nokia 5.3 smartphone\'s epic-sized 6.55-inch HD+ display and incredible quad rear camera that captures stunning pictures even in low light, helps you select your best shot, and creates professional-looking portraits. Capture great detail with the quad camera\'s 13 MP main lens, get everything in the frame with the ultra-wide, 118-degree 5 MP lens, focus in on the tiniest details with the 2 MP macro lens, and create blurred bokeh images with the 2 MP depth sensor. Using AI technology, the Nokia 5.3 takes multiple photos with different lighting and exposure settings, and blends them into one perfect photograph. A front-facing 8 MP camera is great for selfies, and it features Biometric face recognition for quick, secure phone unlock. Stay in the game for longer thanks to the dynamic Qualcomm Snapdragon 665 processor\'s silky smooth graphics and AI-assisted Adaptive Battery that saves energy for the apps you use the most and stays charged for up to 2 days. Featuring Nokia\'s largest screen yet, the Nokia 5.3\'s HD+ screen with 20: 9 display ratio delivers a truly immersive experience while still fitting in your hand and your pocket. The Nokia 5.3 and Google Assistant utilize AI-powered machine learning to learn and adapt to you with every use, and the dedicated Google Assistant button makes it easy to ask questions, update calendars, check traffic, and more.', 11, '\r\n5.3 DS 6/64', '\r\n5.3', '\r\nCHARCOAL', 16.64, '720 x 1600', 'Android Android Q 10', 'Qualcomm Snapdragon 665', 64, 6, 'microSD', '\r\n13MP Rear Camera', '8 MP, f/2.0, (wide)', '\r\n3G, 4G VOLTE, 4G, 2G', 4000, 67, 9, 180, 0, 0),
(18, 'The Nokia 6.1 carries on in the tradition of it\'s predecessors and is built to last, with pure, secure and up-to-date Android. Made from a solid block of 6000 series aluminum, The Nokia 6.1 has distinctive two-tone anodized Diamond cut edges, and a sculpted 2.5D display with Corning Gorilla Glass that provides you with a bright, high contrast 5.5” full-HD screen in more compact screen to body ratio (74%). Built on the latest generation of the highly optimized Qualcomm Snapdragon 630 mobile platform and a 3/32 Memory configuration', 11, 'B07LBPP4J9', '6.1 Plus', 'Blue', 14.73, '2280 x 1080', '\r\nAndroid Oreo 8.1.0', '\r\nQualcomm Snapdragon 636 Octacore', 64, 4, '400GB', '16MP + 5MP', '\r\n16MP Front Camera', '\r\n3G, 4G, 2G', 3630, 71, 8, 151, 0, 0),
(19, 'the Nokia 105 gives you the feeling of a solid, quality phone nestled in the palm of your hand. It\'s good to talk The resilient battery offers up to 15 hours of talk time or a month on standby*, so you can talk from dawn until dusk. Your everyday companion The Nokia 105 is prepared for whatever the day throws at you, with its polycarbonate shell that keeps its color even when scratched. Plus, with a built-in flashlight and pre-loaded games including the classic Snake Xenzia, there\'s never a dark or dull moment. New island keymat with separated keys for greater usability Tough polycarbonate shell Standard headphone jack and MicroUSB charging port Improved 1.8\\\" QQVGA display Nokia Series 30+ software platform Pre-loaded Snake Xenzia game Resilient battery offering up to 15 hours talk time¹ FM radio² 4 MB ROM storage', 11, '\r\nTA-1174/NOKIA 105 DS / 105 ta-1174 ds', 'TA-1174 / TA-1299', '\r\nBlack', 4.57, '\r\n320 x 240', '', '', 4, 4, '', '', '', '\r\n2G', 800, 0, 0, 0, 0, 0),
(20, 'Easy navigation, functional and ergonomic keys, and a 6.09 cm (2.4) screen! The Nokia 150 has everything in place to make your phone usage hassle-free. It also comes with wireless FM and an MP3 player so that you can rely on your music to keep you company. The VGA camera and flash will ensure that your photos come out well. Not to forget, its exterior featuring high-quality, durable polycarbonate makes it a durable phone to have.', 11, '\r\nTA-1235 / 12GMNB21A01', '150 DS 2020', '\r\nBlack', 6.1, '\r\n320 x 240', '\r\nSeries 30+', 'MediaTek', 4, 4, '32', '0.3MP Rear Camera', '', '\r\n2G', 1020, 51, 15, 91, 0, 0),
(21, 'With a large HD+ display, an octa-core processor, adaptive battery technology, efficient front and rear cameras, and many more features such Google Assistant and Fingerprint sensor, the Nokia C3 helps you go through your day effortlessly.', 11, '\r\nSP01Z01Z2249Y', 'C3', '\r\nNordic Blue', 15.21, '\r\n1440 x 720', 'Android 10', 'SC9863A Octa Core', 16, 2, '128', '8MP Rear Camera', '8MP Rear Camera', '\r\n4G VOLTE, 4G, 3G, 2G', 3040, 77, 9, 185, 0, 0),
(22, 'With a responsive 90 Hz refresh rate and the latest HDR10+ technology, the OnePlus 7T’s Fluid Display is smooth, vivid, and incredibly immersive. If it sounds too good to be true, just wait until you see it. Every experience feels more seamless in stunning 90 Hz. It doesn’t just look smoother—it feels smoother, too. 6.55 inch display - Games are more captivating, videos are more cinematic, and everyday tasks are easier in a spacious 20:9 aspect ratio. Certified by world-renowned TÜV Rheinland for superior blue light reduction and viewing safety. * Triple Camera -A camera for every moment: Day or night, near or far, moving or still—no matter where life takes you, always be ready to capture something amazing.', 2, 'B082K96P6W', 'OnePlus 7T', 'Glacier Blue', 16.6, '2400 x 1080', 'Android', 'Qualcomm Snapdragon 865', 256, 8, '256', '48MP+8MP+5MP+2MP', '48', 'GSM, TDS, (B1/2/4/5/8/9/19), FDD-LTE, (B1/2/3/4/5/7/8/12/13/17/18/19/20/26/28/29), (B2/3/5/8), CDMA, TDD-LTE, UMTS, (B34/38/39/40/41), 4G, 2G, (B34/B39), (BC0/BC1)', 3800, 16, 7, 190, 0, 0),
(23, 'The 6.67 inch Fluid AMOLED display on the OnePlus 7 Pro is our most advanced screen ever. Experience unrivalled smoothness and clarity with a 90 Hz refresh rate and QHD+ resolution. Capture life in brand-new ways with a 48 MP main camera, ultra wide angle lens and 3x optical zoom. Combined with smart scene recognition and new Nightscape 2.0 technology, the OnePlus 7 Pro is your personal photo studio.', 2, 'B07HGJK535', 'OnePlus 7 Pro', 'Nebula Blue', 16.9, '3120 x 1440', 'Android 9.0', 'Qualcomm Snapdragon 865', 256, 8, '256', '48 MP', '48MP+8MP+16MP', '4G;FDD;LTE;(B1/2/3/4/5/7/8/12/13/17/18/19/20/25/26/28/29/32/66);TDD-LTE;(B34/38/39/40/41);TDS;(B34/39);UMTS;(B1/2/4/5/8/9/19);CDMA;(BC0/BC1);GSM;(B2/3/5/8)', 4000, 16, 8, 206, 0, 0),
(24, 'OnePlus 8 Pro Onyx Black,? 5G Unlocked Android Smartphone U.S Version, 12GB RAM+256GB Storage, 120Hz Fluid Display,Quad Camera, Wireless Charge, with Alexa Built-in', 2, 'B078BN2H3R', 'OnePlus 8 Pro', 'Glacial Green', 17.2, '\r\nAMOLED', 'Android', 'Qualcomm Snapdragon 865', 256, 8, '256', '48', '48MP+8MP+48MP+5MP', 'GSM, BC0(Roaming), Wi-Fi 802.11 a/b/g/n/ac/ax, 2.4G/5G, Wi-Fi 6, Bluetooth 5.1, support aptX & aptX HD & LDAC & AAC, NFC enabled, LTE-FDD, NR, WCDMA, CDMA, (B1/2/3/4/5/7/8/12/17/18/19/20/26), N78, (B1/B2/B4/B5/B8/B9/B19), 5G, (850/900/1800/1900), (B1/3/41', 4510, 17, 7, 199, 0, 0),
(25, 'we stretched the screen to 6.52\" to give your movies, games, and apps the screen estate they deserve. When you got a big screen, you expect big sound.The Nord rocks a set of powerful dual speakers for a more immersive audio experience. So whether you\'re watching your favorite series or that new movie you\'ve been waiting to see, every moment sounds richer and fuller. A camera system that stacks up.The first step to taking great photos is having the right tools. The Nord comes prepared with a 13 MP main camera for stunning shots, a macro lens for getting up close and personal, and a specialized camera for portrait photos. The power to stop worrying about power.Running around trying to find an outlet as your phone hangs on at 1% is never fun. That\'s why we powered the Nord with a long-lasting 5,000 mAh battery and included an 18W fast charger to make sure it stays powered. Plenty of space to play. Or work. But preferably play.The Nord. 4 GB of RAM helps you zip from streaming to messaging apps to calling the pizza guy to see where your order is, while 64 GB of storage offers lots of space for all your favorite content.', 2, 'B0869855B8', 'OnePlus Nord 5G', 'Marble Blue', 16.4, '2400 x 1080', 'Android', 'Qualcomm Snapdragon 765G 5G mobile platform', 4, 64, '64', '48', '48MP+8MP+5MP+2MP', 'GSM, LTE-FDD, IN, WCDMA, (B1/2/3/4/5/7/8/12/17/18/19/20/26), (B38/39/40/41/46), N78, (B1/B2/B4/B5/B8/B9/B19), 5G, (850/900/1800/1900), MIMO:LTE: B1, 3, 40 NR: N78, LTE-TDD, Network connectivity may vary depending on carrier’s network and related service d', 4115, 16, 7, 184, 0, 0),
(26, 'POCO C3 (Arctic Blue, 64 GB)  (4 GB RAM)', 3, 'MZB07RJIN', 'C3', 'Arctic Blue', 16.59, '1600 x 720', 'Android 10', 'Mediatek Helio G35', 64, 4, '512', '13MP + 2MP + 2MP', '5MP Front Camera', '4G VOLTE, 4G, 3G, 2G', 5000, 77, 9, 194, 0, 0),
(27, 'POCO F1 (Graphite Black, 64 GB)  (6 GB RAM)', 3, 'MZB6645IN', '\r\nF1', 'Graphite Black', 15.7, '2160 x 1080', 'Android Oreo 8.1', 'Qualcomm Snapdragon 845', 64, 6, '256', '\r\n12MP + 5MP', '20MP Front Camera', '3G, 4G VOLTE, 2G', 4000, 75, 9, 180, 0, 0),
(28, 'POCO M2 (Brick Red, 128 GB)  (6 GB RAM)', 3, '\r\nMZB9922IN', '\r\nM2', 'Brick Red', 16.59, '2340 x 1080', 'Android 10', 'MediaTek Helio G80', 128, 6, '512', '13MP + 8MP + 5MP + 2MP', '8MP Front Camera', '4G VOLTE, 4G, 3G, 2G', 5000, 77, 9, 198, 0, 0),
(29, 'POCO M2 Pro (Out of the Blue, 64 GB)  (6 GB RAM)', 3, '\r\nMZB9627IN', 'M2 Pro', 'Out of the Blue', 16.94, '2400 x 1080', '\r\nAndroid 10', 'Qualcomm Snapdragon 720G', 64, 6, '512', '\r\n48MP + 8MP + 5MP + 2MP', '16MP Front Camera', '\r\n4G, 3G, 2G', 5000, 77, 9, 209, 0, 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `product_master`
--
ALTER TABLE `product_master`
  ADD PRIMARY KEY (`product_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `product_master`
--
ALTER TABLE `product_master`
  MODIFY `product_id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=35;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
